-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ledger_entries
(
    id bigserial,
    transaction_id bigint NOT NULL,
    account_id bigint NOT NULL,
    debit bigint NOT NULL,
    credit bigint NOT NULL,
    balance_after bigint NOT NULL,
    created_at date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.security_events
(
    id bigserial,
    event_type character varying NOT NULL,
    user_id bigint NOT NULL,
    ip_address bigint NOT NULL,
    "timestamp" time without time zone NOT NULL,
    metadata character varying NOT NULL,
    PRIMARY KEY (id)
);
END;