-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.notifications
(
    id bigint,
    title character varying NOT NULL,
    message character varying NOT NULL,
    type character varying NOT NULL,
    target_role character varying NOT NULL,
    created_at date NOT NULL,
    created_by date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_notifications
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    notification_id bigint NOT NULL,
    is_read boolean NOT NULL,
    read_at date NOT NULL,
    delivered_at date NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.user_notifications
    ADD FOREIGN KEY (user_id)
    REFERENCES public.notifications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;