-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Clients"
(
    id serial,
    name character varying(50) NOT NULL,
    phone bigint NOT NULL,
    address character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Accounts"
(
    "accountNumber" bigint,
    "clientID" bigint,
    balance bigint NOT NULL,
    "limit" bigint NOT NULL DEFAULT 50000,
    notifications boolean NOT NULL DEFAULT False,
    PRIMARY KEY ("accountNumber")
);

CREATE TABLE IF NOT EXISTS public."Transactions"
(
    "ID" serial,
    status character varying NOT NULL,
    "fromClientID" bigint NOT NULL,
    "toClientID" bigint NOT NULL,
    date date NOT NULL,
    "time" time without time zone,
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Loans"
(
    "ID" serial,
    "AccountID" bigint,
    "Amount" bigint NOT NULL,
    "Left" bigint NOT NULL,
    "Amount_of_Installment" bigint NOT NULL,
    "Date_of_Start" date NOT NULL,
    "Date_of_End" date,
    PRIMARY KEY ("ID")
);

ALTER TABLE IF EXISTS public."Clients"
    ADD FOREIGN KEY (id)
    REFERENCES public."Accounts" ("clientID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Clients"
    ADD FOREIGN KEY (id)
    REFERENCES public."Transactions" ("fromClientID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Clients"
    ADD FOREIGN KEY (id)
    REFERENCES public."Transactions" ("toClientID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Accounts"
    ADD FOREIGN KEY ("accountNumber")
    REFERENCES public."Loans" ("AccountID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;