-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.accounts
(
    account_number bigint NOT NULL,
    client_id bigint,
    balance bigint NOT NULL,
    limitation bigint NOT NULL DEFAULT 50000,
    notifications boolean NOT NULL DEFAULT false,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    token character varying COLLATE pg_catalog."default",
    CONSTRAINT "Accounts_pkey" PRIMARY KEY (account_number)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    phone bigint NOT NULL,
    address character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Clients_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.loans
(
    id serial NOT NULL,
    account_id bigint NOT NULL,
    amount bigint NOT NULL,
    left_amount bigint NOT NULL,
    amount_of_installment bigint NOT NULL,
    date_of_start date NOT NULL,
    date_of_end date,
    CONSTRAINT "Loans_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transactions
(
    id serial NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    from_client_id bigint NOT NULL,
    to_client_id bigint NOT NULL,
    date date NOT NULL,
    time time without time zone,
    CONSTRAINT "Transactions_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.accounts
    ADD CONSTRAINT "Accounts_clientID_fkey" FOREIGN KEY (client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.accounts
    ADD CONSTRAINT "Accounts_clientID_fkey1" FOREIGN KEY (client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.loans
    ADD CONSTRAINT "Loans_AccountID_fkey" FOREIGN KEY (account_id)
    REFERENCES public.accounts (account_number) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.loans
    ADD CONSTRAINT "Loans_AccountID_fkey1" FOREIGN KEY (account_id)
    REFERENCES public.accounts (account_number) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT "Transactions_fromClientID_fkey" FOREIGN KEY (from_client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT "Transactions_fromClientID_fkey1" FOREIGN KEY (from_client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT "Transactions_toClientID_fkey" FOREIGN KEY (to_client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT "Transactions_toClientID_fkey1" FOREIGN KEY (to_client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;