-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Accounts"
(
    "accountNumber" bigint NOT NULL,
    "clientID" bigint,
    balance bigint NOT NULL,
    "limit" bigint NOT NULL DEFAULT 50000,
    notifications boolean NOT NULL DEFAULT false,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    token character varying COLLATE pg_catalog."default",
    CONSTRAINT "Accounts_pkey" PRIMARY KEY ("accountNumber")
);

CREATE TABLE IF NOT EXISTS public."Clients"
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    phone bigint NOT NULL,
    address character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Clients_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Loans"
(
    "ID" serial NOT NULL,
    "AccountID" bigint NOT NULL,
    "Amount" bigint NOT NULL,
    "Left" bigint NOT NULL,
    "Amount_of_Installment" bigint NOT NULL,
    "Date_of_Start" date NOT NULL,
    "Date_of_End" date,
    CONSTRAINT "Loans_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Transactions"
(
    "ID" serial NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    "fromClientID" bigint NOT NULL,
    "toClientID" bigint NOT NULL,
    date date NOT NULL,
    "time" time without time zone,
    CONSTRAINT "Transactions_pkey" PRIMARY KEY ("ID")
);

ALTER TABLE IF EXISTS public."Accounts"
    ADD CONSTRAINT "Accounts_clientID_fkey" FOREIGN KEY ("clientID")
    REFERENCES public."Clients" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Accounts"
    ADD CONSTRAINT "Accounts_clientID_fkey1" FOREIGN KEY ("clientID")
    REFERENCES public."Clients" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Loans"
    ADD CONSTRAINT "Loans_AccountID_fkey" FOREIGN KEY ("AccountID")
    REFERENCES public."Accounts" ("accountNumber") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Loans"
    ADD CONSTRAINT "Loans_AccountID_fkey1" FOREIGN KEY ("AccountID")
    REFERENCES public."Accounts" ("accountNumber") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Transactions"
    ADD CONSTRAINT "Transactions_fromClientID_fkey" FOREIGN KEY ("fromClientID")
    REFERENCES public."Clients" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Transactions"
    ADD CONSTRAINT "Transactions_fromClientID_fkey1" FOREIGN KEY ("fromClientID")
    REFERENCES public."Clients" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Transactions"
    ADD CONSTRAINT "Transactions_toClientID_fkey" FOREIGN KEY ("toClientID")
    REFERENCES public."Clients" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Transactions"
    ADD CONSTRAINT "Transactions_toClientID_fkey1" FOREIGN KEY ("toClientID")
    REFERENCES public."Clients" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;